import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-dim": "#2e5c41",
        "on-secondary": "#fff7f3",
        "error-container": "#fe8b70",
        "on-secondary-fixed": "#493d30",
        "on-tertiary": "#e7ffeb",
        "on-primary-fixed": "#4f3c22",
        "error-dim": "#5c1202",
        "on-tertiary-container": "#326045",
        "inverse-primary": "#f6d8b4",
        "surface-tint": "#715b3e",
        "secondary-fixed-dim": "#e4d1c0",
        "primary-dim": "#644f33",
        "on-tertiary-fixed-variant": "#3c6a4e",
        "outline": "#817a67",
        "surface-container-highest": "#ebe2cb",
        "primary": "#715b3e",
        "surface-dim": "#e3dac0",
        "inverse-surface": "#100e09",
        "on-surface-variant": "#645f4d",
        "on-secondary-fixed-variant": "#67594b",
        "tertiary-fixed-dim": "#b6e9c5",
        "secondary": "#6b5d4f",
        "error": "#9e422c",
        "surface-bright": "#fff9ee",
        "surface-container": "#f5eddd",
        "on-secondary-container": "#5d4f42",
        "tertiary-container": "#c4f7d3",
        "inverse-on-surface": "#a19c93",
        "on-error": "#fff7f6",
        "tertiary-fixed": "#c4f7d3",
        "outline-variant": "#b9b29c",
        "on-primary": "#fff6ef",
        "tertiary": "#3a684d",
        "secondary-dim": "#5e5143",
        "background": "#fff9ee",
        "surface-container-low": "#faf3e5",
        "on-surface": "#373223",
        "on-tertiary-fixed": "#1f4d33",
        "surface-container-high": "#f0e8d4",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#742410",
        "primary-fixed": "#fcdeba",
        "surface-variant": "#ebe2cb",
        "primary-fixed-dim": "#eed0ac",
        "on-primary-fixed-variant": "#6e583c",
        "on-primary-container": "#634e33",
        "secondary-fixed": "#f3dfcd",
        "surface": "#fff9ee",
        "primary-container": "#fcdeba",
        "secondary-container": "#f3dfcd",
        "on-background": "#373223"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "sans": ["var(--font-inter)", "system-ui", "sans-serif"],
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(16px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        skeletonPulse: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.45" },
        },
        overlayFadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        threatPulse: {
          "0%, 100%": { boxShadow: "0 0 0 0 rgba(158, 66, 44, 0.0)" },
          "50%": { boxShadow: "0 0 0 4px rgba(158, 66, 44, 0.08)" },
        },
      },
      animation: {
        fadeIn: "fadeIn 0.5s ease-out forwards",
        slideUp: "slideUp 0.4s ease-out forwards",
        skeletonPulse: "skeletonPulse 1.8s ease-in-out infinite",
        overlayFadeIn: "overlayFadeIn 0.3s ease-out forwards",
        threatPulse: "threatPulse 2s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
export default config;