from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import datetime
from enum import Enum

from app.schemas.decision_payload import DecisionPayload
from app.schemas.policy_compliance_record import PolicyComplianceRecord
from app.schemas.contradiction_record import ContradictionRecord
from app.schemas.missing_evidence_record import MissingEvidenceRecord
from app.schemas.assumption_record import AssumptionRecord
from app.schemas.decision_replay import DecisionReplay
from app.schemas.executive_recommendation import ExecutiveRecommendation
from app.schemas.confidence_waterfall import ConfidenceWaterfall

class AuditStatus(str, Enum):
    APPROVED = "APPROVED"
    WARNING = "WARNING"
    REJECTED_CRITICAL = "REJECTED_CRITICAL"

class ChallengeReview(BaseModel):
    """
    Structured outcome of the adversarial Audit Challenge debate mode.
    """
    supporting_argument: str = Field(
        ...,
        description="The strongest logical argument supporting the decision."
    )
    opposing_argument: str = Field(
        ...,
        description="The strongest adversarial argument against the decision."
    )
    confidence_adjustment: float = Field(
        ...,
        description="The change in confidence (-1.0 to 1.0) after adversarial debate."
    )
    challenge_summary: str = Field(
        ...,
        description="A short evaluation summary of the challenge mode findings."
    )

    class Config:
        from_attributes = True

class DecisionTimeline(BaseModel):
    """
    Represents the sequential steps and variables evaluated throughout the audit cycle.
    """
    decision_step: str = Field(
        ...,
        description="Name of the audit phase or current step."
    )
    evidence_used: List[str] = Field(
        default_factory=list,
        description="List of evidence snippets/sources used in this step."
    )
    evidence_ignored: List[str] = Field(
        default_factory=list,
        description="List of evidence snippets/sources ignored or overridden."
    )
    assumptions_made: List[str] = Field(
        default_factory=list,
        description="Assumptions detected during step validation."
    )
    counterfactuals: List[str] = Field(
        default_factory=list,
        description="Hypothetical alternatives simulated."
    )
    final_recommendation: str = Field(
        ...,
        description="Recommendation summary state at this step."
    )

    class Config:
        from_attributes = True

class AuditFindings(BaseModel):
    """
    Consolidated findings block raised by the multi-agent auditing debate.
    """
    policy_compliance: List[PolicyComplianceRecord] = Field(
        default_factory=list,
        description="Policy alignment audits performed against organization rules/SOPs."
    )
    contradictions: List[ContradictionRecord] = Field(
        default_factory=list,
        description="Factual, internal, or business policy contradiction events."
    )
    missing_evidence: List[MissingEvidenceRecord] = Field(
        default_factory=list,
        description="Omitted variables or files needed to verify the decision logically."
    )
    assumptions: List[AssumptionRecord] = Field(
        default_factory=list,
        description="Logical leaps or unverified heuristic premises used by the decision agent."
    )

    class Config:
        from_attributes = True

class DecisionAuditReport(BaseModel):
    """
    The master audit schema generated by Trust Console IQ for auditing AI decisions.
    """
    audit_id: str = Field(
        ..., 
        description="Unique identifier for this decision auditing run."
    )
    timestamp: datetime = Field(
        default_factory=datetime.utcnow,
        description="The time at which the audit was completed."
    )
    decision_context: DecisionPayload = Field(
        ..., 
        description="The source AI agent payload and metadata."
    )
    overall_trust_score: float = Field(
        ..., 
        ge=0.0, 
        le=1.0, 
        description="Trust calibration score (0.0 to 1.0) indicating decision reliability and data backing."
    )
    overall_risk_score: float = Field(
        ..., 
        ge=0.0, 
        le=1.0, 
        description="Risk safety score (0.0 to 1.0) indicating liability exposure and parameter ambiguity."
    )
    audit_status: AuditStatus = Field(
        ..., 
        description="Governance output rating representing decision feasibility."
    )
    findings: AuditFindings = Field(
        ..., 
        description="Structural audit details compiling policy checks, contradictions, missing inputs, and assumptions."
    )
    decision_replay: DecisionReplay = Field(
        ..., 
        description="Explainability data showing evidence influence matrices and counterfactual outcomes."
    )
    executive_recommendation: ExecutiveRecommendation = Field(
        ..., 
        description="Actionable verdict gating and human mitigation instructions."
    )
    challenge_review: Optional[ChallengeReview] = Field(
        None,
        description="The results of the Adversarial Challenge validation phase."
    )
    decision_timeline: List[DecisionTimeline] = Field(
        default_factory=list,
        description="Trace of the historical step evaluation state."
    )
    evidence_influence_ranking: List[str] = Field(
        default_factory=list,
        description="Ranked summary of sources ordered by their audit influence weight."
    )
    confidence_waterfall: Optional[ConfidenceWaterfall] = Field(
        None,
        description="Confidence adjustments waterfall trace data."
    )
    calibration_trace: List[str] = Field(
        default_factory=list,
        description="Explanations logged step-by-step during score calibration."
    )
    governance_rule_results: List[str] = Field(
        default_factory=list,
        description="Descriptions of triggers activated in the Governance Rules Engine."
    )

    class Config:
        from_attributes = True
