from pydantic import BaseModel, Field
from typing import Optional

class EvidenceRecord(BaseModel):
    """
    Structured ground-truth evidence record sourced from either corporate databases (Fabric IQ) or public web.
    """
    source: str = Field(
        ..., 
        description="The source identifier, system, or website."
    )
    title: str = Field(
        ..., 
        description="The header or name of the source material."
    )
    url: Optional[str] = Field(
        None, 
        description="The URL reference if sourced from public web."
    )
    evidence_text: str = Field(
        ..., 
        alias="evidence",
        description="The actual snippet of supporting or contradicting content."
    )
    similarity: float = Field(
        ..., 
        description="The semantic similarity score of the retrieved snippet."
    )
    support_label: Optional[str] = Field(
        None, 
        description="NLI classification: 'entailment' (support), 'contradiction', or 'neutral'."
    )
    support_score: Optional[float] = Field(
        None, 
        description="Confidence score of the NLI classification."
    )
    origin: str = Field(
        "public_web", 
        description="Origin of the data. Must be either 'fabric_internal' or 'public_web'."
    )
    source_trust: Optional[float] = Field(
        None, 
        description="Calculated trust multiplier for the evidence source."
    )
    evidence_summary: Optional[str] = Field(
        None, 
        description="The summarized content generated by the summarization system."
    )

    class Config:
        populate_by_name = True
        from_attributes = True
