from pydantic import BaseModel, Field
from typing import List
from enum import Enum

class RecommendationAction(str, Enum):
    PROCEED = "PROCEED"
    HOLD_FOR_REVIEW = "HOLD_FOR_REVIEW"
    DENY = "DENY"

class ExecutiveRecommendation(BaseModel):
    """
    Final governance verdict generated by Trust Console IQ for human reviewers.
    """
    summary: str = Field(
        ..., 
        description="A concise executive summary explaining the auditing decision reasoning."
    )
    recommended_action: RecommendationAction = Field(
        ..., 
        description="The actionable recommendation gate (PROCEED, HOLD_FOR_REVIEW, or DENY)."
    )
    remediation_steps: List[str] = Field(
        default_factory=list,
        description="Chronological actions a human operator should perform to resolve audit warnings."
    )

    class Config:
        from_attributes = True
